e_portal/e_app/urls.py
from django.contrib import admin
from django.urls import path, include
from e_app import views

app_name = 'e_app'

urlpatterns = [
    path('register/', views.register, name="register"),
    path('user_login/', views.user_login, name='user_login'),
    path('courses/', views.courses, name="courses"),
]

e_portal/e_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from e_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('eapp/', include('e_app.urls')),
    path('logout/', views.user_logout, name='logout')
]

e_portal/e_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    mobile = models.CharField(max_length=15, null=True)
    clgname = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.user.username


class CourseType(models.Model):
    course_type = models.CharField(max_length=50)

    def __str__(self):
        return self.course_type


class CourseDes(models.Model):
    course_name = models.CharField(max_length=100, null=True)
    course_id = models.IntegerField(null=True)
    course_type = models.ForeignKey(CourseType, on_delete=models.CASCADE)
    course_des = models.CharField(max_length=200, null=True)
    course_year = models.DateField(null=True)
    course_price = models.CharField(max_length=10, null=True)

    def __str__(self):
        return self.course_name


class RegCourses(models.Model):
    user_name = models.CharField(max_length=100)
    course_id = models.CharField(max_length=100)

    def __str__(self):
        return self.user_name

e_portal/e_app/forms.py
from django import forms
from django.contrib.auth.models import User
from e_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('mobile', 'clgname')

e_portal/e_app/views.py
from django.shortcuts import render
from e_app.forms import UserForm, UserProfileInfoForm
from .models import *
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.


def index(request):
    return render(request, 'e_app/index.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('ACCOUNT NOT ACTIVE')
        else:
            return HttpResponse("INVALID LOGIN DETAILS SUPPPLIED")

    return render(request, 'e_app/login.html', {})


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:

        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'e_app/registration.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


def courses(request):
    user = request.user

    courses = CourseDes.objects.all()

    if 'Full stack django web development' in request.POST:
        reg = RegCourses.objects.create(
            user_name=user, course_id='Full stack django web development')

    if 'Introduction to Machine learning' in request.POST:
        reg = RegCourses.objects.create(
            user_name=user, course_id='Introduction to Machine learning')

    if 'Flutter and Dart beginners guide' in request.POST:
        reg = RegCourses.objects.create(
            user_name=user, course_id='Flutter and Dart beginners guide')

    if 'Python bootcamp' in request.POST:
        reg = RegCourses.objects.create(
            user_name=user, course_id='Python bootcamp')

    return render(request, 'e_app/courses.html', {'courses': courses, 'user': user})

e_portal/templates/e_app/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
      <div class="navbar-nav">
        {# Django Home Link / Admin Link / Register Link#}
        <a class="navbar-brand" href="{% url 'index' %}">E-portal</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="{% url 'e_app:register' %}">Register</a>
        <a class="nav-item nav-link" href="{% url 'e_app:courses' %}">Courses</a>

        {# Some logic on what to display for last item#}
        {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        {% else %}
          <a class="nav-link" href="{% url 'e_app:user_login' %}">Login</a>
        {% endif %}
      </div>
    </nav>

    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>


  </body>
</html>

e_portal/templates/e_app/courses.html
{% extends "e_app/base.html" %}
{% load static %}
{% block body_block %}

<div class="container">
  
    <div class="row">
      <div class="col-lg-4">
    <div class="card border-info mb-3" style="max-width: 18rem;">
      <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="{% static 'images/web.jpg' %}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">Full stack django web development</h5>
            <p class="card-text">This is a full stack web development using python and django.</p>
            <form enctype="multipart/form-data" method="POST">
              {% csrf_token %}
              <input type="submit" class="btn btn-primary" name="Full stack django web development" value="Register">
            </form>
            
          </div>
        </div>
      </div>
    </div>


    <div class="col-lg-4">
      <div class="card border-info mb-3" style="max-width: 18rem;">
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="{% static 'images/machine.jpeg' %}" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title">Introduction to Machine learning</h5>
              <p class="card-text">This is a introductory course for Machine learning</p>
              <form enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" name="Introduction to Machine learning" value="Register">
              </form>
            </div>
          </div>
        </div>
        </div>

        
    
      <div class="col-lg-4">
    <div class="card border-info mb-3" style="max-width: 18rem;">
      <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="{% static 'images/app.jpg' %}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">Flutter and Dart beginners guide</h5>
            <p class="card-text">This is a beginner tutorial for flutter and dart .</p>
            <form enctype="multipart/form-data" method="POST">
              {% csrf_token %}
              <input type="submit" class="btn btn-primary" name="Flutter and Dart beginners guide" value="Register">
            </form>
          </div>
        </div>
      </div>
      </div>
   
      <div class="col-lg-4">
        <div class="card border-info mb-3" style="max-width: 18rem;">
          <div class="card" style="width: 18rem;">
              <img class="card-img-top" src="{% static 'images/python.jpg' %}" alt="Card image cap">
              <div class="card-body">
                <h5 class="card-title">Python bootcamp</h5>
                <p class="card-text">In this course you will learn python from basic to advanced.</p>
                <form enctype="multipart/form-data" method="POST">
                  {% csrf_token %}
                  <input type="submit" class="btn btn-primary" name="Python bootcamp" value="Register">
                </form>
              </div>
            </div>
          </div>
          </div>
        
    
     

    
    
  
</div>

{% endblock %}

e_portal/templates/e_app/index.html
{% extends "e_app/base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>Welcome to E-Portal</h1>
    {% if user.is_authenticated %}
        <h2>Welcome {{ user.username }}!</h2>
    {% else %}
        <h2>Welcome to the site!</h2>
    {% endif %}
  </div>
</div>

{% endblock %}

e_portal/templates/e_app/login.html
{% extends 'e_app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'e_app:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

e_portal/templates/e_app/registration.html
{% extends "e_app/base.html" %}
{% load static %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}